name: owvision
description: Software system to record, archive, analyze and share your weather station's data with anyone!
version: 0.0.2
repository: https://github.com/open-weather-vision/owvision

environment:
    sdk: ^3.9.2

workspace:
    - daemon
    - recorder
    - shared
    - daemon/clients/daemon_client_dart
dev_dependencies:
    yaml: ^3.1.3
    yaml_edit: ^2.2.3
    args: ^2.7.0
    shared: any
    chalk: ^1.2.1
    chalkdart: ^3.0.5
    daemon: any
    path: ^1.9.1
