name: owvision_daemon_client_dart
version: 0.0.2
description: OpenAPI API client
homepage: https://open-weather-vision.github.io/owvision/


environment:
  sdk: ^3.9.2

dependencies:
  dio: '^5.7.0'
  copy_with_extension: ^11.0.0
  json_annotation: '^4.9.0'

dev_dependencies:
  build_runner: any
  copy_with_extension_gen: ^11.0.0
  json_serializable: '^6.9.3'
  test: '^1.16.0'
resolution: workspace
