name: recorder
description: A sample command-line application.
version: 0.0.8
publish_to: "none"

environment:
    sdk: ^3.9.2

# Add regular dependencies here.
dependencies:
    args: ^2.7.0
    chalkdart: ^3.0.5
    fixnum: ^1.1.1
    get_it: ^9.2.0
    grpc: ^5.1.0
    injectable: ^2.7.1+4
    interact: ^2.2.0
    json_annotation: ^4.9.0
    logging: ^1.3.0
    open_meteo: ^3.0.0
    path: ^1.9.0
    protobuf: ^6.0.0
    shared: any

dev_dependencies:
    lints: ^6.0.0
    test: ^1.25.6
    injectable_generator: ^2.6.1
    build_runner: ^2.10.5
    json_serializable: ^6.11.4

resolution: workspace

scripts:
    "build": "dart run build_runner build"
